name: CI Build
on:
  push:
    branches: [main]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: ["deepnote", "not_deepnote"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip

      - name: Install tox
        run: pip install tox

      - name: Cache tox environment dependencies
        uses: actions/cache@v4
        with:
          path: .tox/${{ matrix.tox-env }}
          key: tox-${{ matrix.tox-env }}-${{ hashFiles('pyproject.toml', format('.tox/{0}/constraints.txt', matrix.tox-env)) }}
          restore-keys: |
            tox-${{ matrix.tox-env }}

      # TODO: use test fixtures instead of fetching real data in tests
      - name: Cache USGS rasters
        uses: actions/cache@v4
        with:
          path: .usgs_cache/**/*.tif
          key: usgs-cache-${{ hashFiles('.usgs_cache/**/*.tif') }}
          restore-keys: |
            usgs-cache-

      - name: Run Tests
        run: tox run -e ${{ matrix.tox-env }}
        env:
          PYTEST_ADDOPTS: "-vv"
